export const globalCountries = [
  { name: "Thailand", code: "+66", flag: "🇹🇭", idType: "ID Card / Passport" },
  {
    name: "United Arab Emirates",
    code: "+971",
    flag: "🇦🇪",
    idType: "Emirates ID / Passport",
  },
  {
    name: "Saudi Arabia",
    code: "+966",
    flag: "🇸🇦",
    idType: "Iqama / Passport",
  },
  {
    name: "Japan",
    code: "+81",
    flag: "🇯🇵",
    idType: "My Number Card / Passport",
  },
  { name: "South Korea", code: "+82", flag: "🇰🇷", idType: "ARC / Passport" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾", idType: "MyKad / Passport" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩", idType: "KTP / Passport" },
  { name: "Turkey", code: "+90", flag: "🇹🇷", idType: "TC Kimlik / Passport" },
  { name: "United States", code: "+1", flag: "🇺🇸", idType: "SSN / Passport" },
  {
    name: "United Kingdom",
    code: "+44",
    flag: "🇬🇧",
    idType: "Biometric / Passport",
  },
  { name: "France", code: "+33", flag: "🇫🇷", idType: "National ID / Passport" },
  {
    name: "Germany",
    code: "+49",
    flag: "🇩🇪",
    idType: "Personalausweis / Passport",
  },
  {
    name: "Switzerland",
    code: "+41",
    flag: "🇨🇭",
    idType: "ID Card / Passport",
  },
  {
    name: "Cambodia",
    code: "+855",
    flag: "🇰🇭",
    idType: "National ID / Passport",
  },
  { name: "Singapore", code: "+65", flag: "🇸🇬", idType: "NRIC / Passport" },
];
