name: Deep Clean and Format

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prettier Auto-Fix
        uses: creyder/prettier_action@v4.3
        with:
          prettier_options: >
            --write "src/**/*.{js,jsx,json,css}" 
            package.json 
            app.json 
            --ignore-unknown 
            --ignore-path .gitignore
          
          install_plugins: false
          commit_message: "chore: deep clean and formatting [skip ci]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
